# Generated by Django 5.2.15 on 2026-07-01 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
        ('packages', '0005_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_enquiries', to='packages.package'),
        ),
    ]
