# Generated by Django 5.2.15 on 2026-07-01 10:45

from django.db import migrations, models


def backfill_duration_days(apps, schema_editor):
    Package = apps.get_model("packages", "Package")
    from packages.search import extract_duration_days

    for package in Package.objects.all().iterator():
        days = extract_duration_days(package.duration or "")
        if package.duration_days != days:
            Package.objects.filter(pk=package.pk).update(duration_days=days)


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration_days',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, help_text='Auto-calculated from duration for sorting and filters.', null=True),
        ),
        migrations.RunPython(backfill_duration_days, migrations.RunPython.noop),
    ]
