# Generated by Django 5.2.15 on 2026-07-01 11:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_duration_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='destination',
        ),
        migrations.AlterUniqueTogether(
            name='packageday',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='packageday',
            name='package',
        ),
        migrations.RemoveField(
            model_name='packageexclusion',
            name='package',
        ),
        migrations.RemoveField(
            model_name='packagehighlight',
            name='package',
        ),
        migrations.RemoveField(
            model_name='packageinclusion',
            name='package',
        ),
        migrations.RemoveField(
            model_name='packageprice',
            name='package',
        ),
        migrations.RemoveField(
            model_name='packagereview',
            name='package',
        ),
        migrations.AlterModelOptions(
            name='packagecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Package categories'},
        ),
        migrations.AlterModelOptions(
            name='packageimage',
            options={'ordering': ['display_order'], 'verbose_name': 'Package photo', 'verbose_name_plural': 'Package photos'},
        ),
        migrations.RemoveField(
            model_name='package',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='package',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='package',
            name='compare_price',
        ),
        migrations.RemoveField(
            model_name='package',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='package',
            name='legacy_image_prefix',
        ),
        migrations.RemoveField(
            model_name='package',
            name='list_image',
        ),
        migrations.RemoveField(
            model_name='package',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='package',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='package',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='package',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='package',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='package',
            name='rating_score',
        ),
        migrations.RemoveField(
            model_name='packagecategory',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='packagecategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='packagecategory',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='packageimage',
            name='caption',
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Full package description.'),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.CharField(blank=True, help_text='Display text, e.g. 09 NIGHTS / 10 DAYS (used for filters/sort).', max_length=120),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration_days',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, help_text='Auto-calculated from duration — not shown in admin.', null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short summary for listings.', max_length=500),
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='PackageDay',
        ),
        migrations.DeleteModel(
            name='PackageExclusion',
        ),
        migrations.DeleteModel(
            name='PackageHighlight',
        ),
        migrations.DeleteModel(
            name='PackageInclusion',
        ),
        migrations.DeleteModel(
            name='PackagePrice',
        ),
        migrations.DeleteModel(
            name='PackageReview',
        ),
    ]
