# Generated by Django 5.1.15 on 2026-07-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0005_testimonial"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="hero_banner",
            field=models.ImageField(
                blank=True,
                help_text="Hero banner only — upload exactly 1920×400 px (same size as all inner-page heroes).",
                null=True,
                upload_to="packages/hero/",
            ),
        ),
    ]
