# Generated by Django 5.1.15 on 2026-07-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0006_package_hero_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="hero_banner_mobile",
            field=models.ImageField(
                blank=True,
                help_text="Mobile hero — upload exactly 828×400 px. Falls back to desktop hero if empty.",
                null=True,
                upload_to="packages/hero/mobile/",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="hero_banner",
            field=models.ImageField(
                blank=True,
                help_text="Desktop hero — upload exactly 1920×400 px.",
                null=True,
                upload_to="packages/hero/desktop/",
            ),
        ),
    ]
