# Generated by Django 5.2.15 on 2026-06-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Admin label for this banner', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Small script line above heading', max_length=255)),
                ('heading', models.CharField(help_text='Main headline (basic HTML allowed: em, br, strong)', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('desktop_image', models.ImageField(upload_to='banners/')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='banners/mobile/')),
                ('background_video', models.FileField(blank=True, null=True, upload_to='banners/videos/')),
                ('text_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10)),
                ('text_color', models.CharField(choices=[('white', 'White'), ('dark', 'Dark'), ('primary', 'Primary Blue'), ('secondary', 'Secondary')], default='white', max_length=20)),
                ('overlay_opacity', models.DecimalField(decimal_places=2, default=0.3, max_digits=3)),
                ('primary_button_text', models.CharField(blank=True, max_length=100)),
                ('primary_button_url', models.CharField(blank=True, max_length=255)),
                ('primary_button_style', models.CharField(choices=[('primary', 'Primary'), ('outline', 'Outline'), ('glass', 'Glass')], default='primary', max_length=20)),
                ('secondary_button_text', models.CharField(blank=True, max_length=100)),
                ('secondary_button_url', models.CharField(blank=True, max_length=255)),
                ('secondary_button_style', models.CharField(choices=[('primary', 'Primary'), ('outline', 'Outline'), ('glass', 'Glass')], default='outline', max_length=20)),
                ('animation', models.CharField(choices=[('fade', 'Fade'), ('slide', 'Slide'), ('zoom', 'Zoom'), ('kenburns', 'Ken Burns')], default='fade', max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order', 'id'],
            },
        ),
    ]
