# Generated by Django 5.2.15 on 2026-06-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='heading',
            field=models.CharField(blank=True, help_text='Main headline (basic HTML allowed: em, br, strong)', max_length=255),
        ),
    ]
