# Generated by Django 5.2.15 on 2026-07-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_banner_heading_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_from',
            field=models.EmailField(blank=True, help_text='From address on outgoing mail. Defaults to the public contact email.', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_notification_bcc',
            field=models.EmailField(blank=True, help_text='Optional BCC on staff notification emails.', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_notification_to',
            field=models.EmailField(blank=True, help_text='Inbox for contact form submissions. Defaults to the public contact email.', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_enabled',
            field=models.BooleanField(default=False, help_text='Enable real SMTP delivery. When off, messages print to the server console.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='e.g. smtp.gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False, help_text='Use for port 465 (SSL). Do not enable both TLS and SSL.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, help_text='Typically on for port 587.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
