# Generated by Django 5.1.15 on 2026-07-02 08:44

from django.db import migrations, models


PAGE_KEYS = [
    "services",
    "gallery",
    "packages_all",
    "packages_domestic",
    "packages_international",
    "packages_pilgrim",
    "about",
    "contact",
    "landing_wayanad",
    "landing_international",
    "landing_pilgrim",
]


def seed_page_heroes(apps, schema_editor):
    PageHero = apps.get_model("core", "PageHero")
    for page_key in PAGE_KEYS:
        PageHero.objects.get_or_create(page_key=page_key)


def unseed_page_heroes(apps, schema_editor):
    PageHero = apps.get_model("core", "PageHero")
    PageHero.objects.filter(page_key__in=PAGE_KEYS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_import_env_smtp"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page_key",
                    models.CharField(
                        choices=[
                            ("services", "Services"),
                            ("gallery", "Gallery"),
                            ("packages_all", "All Packages"),
                            ("packages_domestic", "Domestic Packages"),
                            ("packages_international", "International Packages"),
                            ("packages_pilgrim", "Pilgrim Packages"),
                            ("about", "About Us"),
                            ("contact", "Contact"),
                            ("landing_wayanad", "Wayanad Landing"),
                            ("landing_international", "International Landing"),
                            ("landing_pilgrim", "Pilgrim Landing"),
                        ],
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload exactly 1920×400 px (one image per page).",
                        upload_to="page-heroes/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="When off, the site uses the built-in placeholder for this page.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page hero",
                "verbose_name_plural": "Page heroes",
                "ordering": ["page_key"],
            },
        ),
        migrations.RunPython(seed_page_heroes, unseed_page_heroes),
    ]
