# Generated by Django 5.1.15 on 2026-07-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_import_static_page_heroes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagehero",
            name="mobile_image",
            field=models.ImageField(
                blank=True,
                help_text="Mobile — upload exactly 828×400 px. Falls back to the desktop image if empty.",
                upload_to="page-heroes/mobile/",
            ),
        ),
        migrations.AlterField(
            model_name="pagehero",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Desktop — upload exactly 1920×400 px.",
                upload_to="page-heroes/desktop/",
            ),
        ),
        migrations.AlterField(
            model_name="pagehero",
            name="page_key",
            field=models.CharField(
                choices=[
                    ("services", "Services (/services/)"),
                    ("gallery", "Gallery (/gallery/)"),
                    ("packages_all", "All Packages — list (/packages/)"),
                    (
                        "packages_domestic",
                        "Domestic Packages — list (/packages/?category=domestic)",
                    ),
                    (
                        "packages_international",
                        "International Packages — list (/packages/?category=international)",
                    ),
                    (
                        "packages_pilgrim",
                        "Pilgrim Packages — list (/packages/?category=pilgrim)",
                    ),
                    ("about", "About Us (/about/)"),
                    ("contact", "Contact (/contact/)"),
                    ("landing_wayanad", "Wayanad — landing page (/pages/wayanad/)"),
                    (
                        "landing_international",
                        "International — landing page (/pages/international-packages/)",
                    ),
                    (
                        "landing_pilgrim",
                        "Pilgrim — landing page (/pages/pilgrim-packages/)",
                    ),
                ],
                max_length=40,
                unique=True,
            ),
        ),
    ]
