# Generated by Django 5.2.15 on 2026-07-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='album',
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Gallery photo', 'verbose_name_plural': 'Gallery photos'},
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='legacy_filename',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='GalleryAlbum',
        ),
    ]
