# Generated by Django 5.2.15 on 2026-07-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staticpage",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Deprecated — use Admin → Core → Page heroes for banner images.",
                null=True,
                upload_to="pages/",
            ),
        ),
    ]
